name: Gradle Dependency Submission
on:
  push:
    branches:
      - master
      
jobs:
  gradle-dependency-submission:
    name: Dependencies
    runs-on: ubuntu-latest
    permissions: # The Dependency Submission API requires write permission
      contents: write
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v3

      - name: Run snapshot action
        uses: mikepenz/gradle-dependency-submission@{latest}
        with:
          gradle-build-module: ":app"
          
